### PR TITLE
Implement --at-least-one-of

### LINKED ISSUE #182: Maybe: require one of a set of features in `--feature-powerset`
As an example, consider a crate which uses a hashmap, and has a feature `std` to use the std hashmap and a feature `hashbrown` to use the hashmap from hashbrown. This crate *requires* that at least one of `std` or `hashbrown` are used, so `--feature-powerset` won't work as-is, because it will want to test the noncompiling `--no-default-features` configuration. There are other feature flags which the library would like to test as well, so `--exclude-no-default-features` isn't sufficient.

Currently, the crate can use two runs of `cargo hack`, e.g.

```text
cargo hack --feature-powerset --features=std check
cargo hack --feature-powerset --features=hashbrown check
```

If there's more than one such set of "require one of." you can see how this could get complicated quickly, basically being its own separate powerset.

cargo-hack could potentially provide a flag `--required-features-group std,hashbrown` with the semantics of discarding any feature set which does not include at least one of the listed features in order to make this situation easier to test.

### PR DESCRIPTION
**Pull request by kornelski**
Skips powersets that don't contain any of the specified features. Can be used to test `cfg-if` chains of features where the last `else` is a compile error.

Fixes #182

### CODE REVIEW

**Comment by taiki-e** [comment]
Thanks!

Could you add a test for this? (I think we can add a test that processes the input in the same way as [src/main.rs#L244-L258](https://github.com/taiki-e/cargo-hack/pull/193/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR244-R258) and checks the result, to the tests module in features.rs.)

**Comment by kornelski** [comment]
Change in MSRV is unrelated. Could be fixed with `cargo update -p ctrlc --precise 3.1.4`, but I don't see how this could work without lockfile and with your custom msrv workflow.

**Comment by taiki-e** [comment]
I fixed the MSRV issue on the main branch, could you rebase?

**Review by taiki-e — APPROVED** [review]

**Comment by taiki-e** [comment]
Published in 0.6.5. Thanks @kornelski!

**Pull request merged**
