### PR TITLE
Stop commit of Cargo.lock

### PR DESCRIPTION
**Pull request by taiki-e**
If you want to use cargo-hack with versions of dependencies at the time of release, please download the compiled binary from GitHub Releases.
Upload of the compiled binary is part of the automated release process and installation from GitHub Releases is much faster than installation from the source.

To install cargo-hack from GitHub Releases:

```sh
# Linux
curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-x86_64-unknown-linux-musl.tar.gz | tar xzf -
# macOS
curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-x86_64-apple-darwin.tar.gz | tar xzf -
# Windows
curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-x86_64-pc-windows-msvc.tar.gz | tar xzf -

# or, detect host os (works on all of the above platform)
host=$(rustc -Vv | grep host | sed 's/host: //')
curl -LsSf https://github.com/taiki-e/cargo-hack/releases/latest/download/cargo-hack-"$host".tar.gz | tar xzf -
```

### CODE REVIEW

**Comment by taiki-e** [comment]
`cargo install` ignores `Cargo.lock` by default and uses the latest dependencies.
As we committing `Cargo.lock`, the current CI settings cannot guarantee that crate is working properly with the latest dependencies at the time of release.

Of course, we can guarantee this by making CI complicate, but given that the cargo-hack is small and [no one seems to be installing cargo-hack with the `--locked` flag](https://grep.app/search?q=cargo-hack.%2A--locked&regexp=true), I think it's okay to do this for now.

If someone needs it in the future, please comment on this PR or open a new issue.

**Comment by taiki-e** [comment]
I noticed that cargo automatically publishes Cargo.lock when it releases a binary crate.
Therefore, there are no users who may be badly affected by this change.

```console
$ cargo install cargo-hack --locked
    Updating crates.io index
  Downloaded cargo-hack v0.5.8
  Downloaded 1 crate (46.1 KB) in 1.22s
  Installing cargo-hack v0.5.8
   Compiling autocfg v1.0.1
   Compiling libc v0.2.103
   Compiling serde v1.0.130
   Compiling ryu v1.0.5
   Compiling serde_json v1.0.68
   Compiling cfg-if v1.0.0
   Compiling anyhow v1.0.44
   Compiling bitflags v1.3.2
   Compiling itoa v0.4.8
   Compiling termcolor v1.1.2
   Compiling memoffset v0.6.4
   Compiling nix v0.23.0
   Compiling atty v0.2.14
   Compiling toml v0.5.8
   Compiling ctrlc v3.2.1
   Compiling cargo-hack v0.5.8
    Finished release [optimized] target(s) in 13.44s
  Installing /Users/taiki/.cargo/bin/cargo-hack
   Installed package `cargo-hack v0.5.8` (executable `cargo-hack`)
$ cargo install cargo-hack -f
    Updating crates.io index
  Installing cargo-hack v0.5.8
   Compiling libc v0.2.112
   Compiling autocfg v1.0.1
   Compiling serde v1.0.132
   Compiling bitflags v1.3.2
   Compiling serde_json v1.0.73
   Compiling cfg-if v1.0.0
   Compiling anyhow v1.0.52
   Compiling ryu v1.0.9
   Compiling itoa v1.0.1
   Compiling termcolor v1.1.2
   Compiling memoffset v0.6.5
   Compiling nix v0.23.1
   Compiling atty v0.2.14
   Compiling toml v0.5.8
   Compiling ctrlc v3.2.1
   Compiling cargo-hack v0.5.8
    Finished release [optimized] target(s) in 14.36s
   Replacing /Users/taiki/.cargo/bin/cargo-hack
    Replaced package `cargo-hack v0.5.8` with `cargo-hack v0.5.8` (executable `cargo-hack`)
```

So, I'll remove the mention of this change from the changelog.

**Comment by jirutka** [comment]
> Therefore, there are no users who may be badly affected by this change.

That’s not true, (linux) distributions uses this file. We build rust crates from the source repository, not crates.io. Can you please revert this and put Cargo.lock back where it should be, into the repository?

**Comment by taiki-e** [comment]
As discussed in https://github.com/taiki-e/cargo-llvm-cov/pull/152, I'm open to accepting a PR that commits lockfile if non-cargo package managers require it.

**Pull request merged**
