### PR TITLE
Add skip command

### LINKED ISSUE #24: request: Add a `--skip` subcommand
## Motivation

`--feature-powerset` was added recently and it has been really helpful.
Unfortunately, if there is a feature that doesn't need to be tested in the
combinations it's not possible to skip. Each additional feature that is tested
in the powerset doubles the run-time so it can be costly as the number of
features grows.

## Solution

Add a `--skip` subcommand that can be paired with `--each-feature` or
`--feature-powerset`. The latter subcommands would filter out any features
passed in `--skip` before running their own logic.

I wanted to open the issue before sending in a PR incase @taiki-e had any
thoughts? If this is something you are okay with adding, I can send in a quick
change to add it. It should be fairly straightforward.

### PR DESCRIPTION
**Pull request by kleimkuhler**
Closes #24 

Signed-off-by: Kevin Leimkuhler <kleimkuhler@icloud.com>

### CODE REVIEW

**Comment by taiki-e** [comment]
Thanks!

bors r+

**Comment by taiki-e** [comment]
bors retry

**Comment by kleimkuhler** [comment]
@taiki-e Any chance a new release could be cut for this? I'd like a CI build to depend on this without having to specify the specific commit.

**Comment by taiki-e** [comment]
Published in 0.3.3

**Comment by kleimkuhler** [comment]
Ah awesome thank you!!

**Pull request merged**
