### PR TITLE
ci: Distribute compiled binary files via GitHub release

### PR DESCRIPTION
**Pull request by taiki-e**
If you install locally, I basically recommend using `cargo install`, but given that one of cargo-hack's main purposes is to use it in CI, it makes sense to distribute the compiled binary files.

### CODE REVIEW

**Comment by taiki-e** [comment]
To install latest release:

```sh
# get latest release and host toolchain
version=$(curl -LsSf https://api.github.com/repos/taiki-e/cargo-hack/releases/latest | jq -r '.name')
host=$(rustc -Vv | grep host | sed 's/host: //')

# linux/macos
curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.tar.gz | tar xzf -

# windows
curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.zip -o cargo-hack.zip
7z x cargo-hack.zip
```

**Comment by jhpratt** [comment]
I will say, we think alike. I've been contemplating whether to file a PR for a couple days for this exact thing 😁

**Comment by jhpratt** [comment]
For those (like myself) looking for a single script to download it, I just added some conditionals to the above.

```bash
version=$(curl -LsSf https://api.github.com/repos/taiki-e/cargo-hack/releases/latest | jq -r '.name')
host=$(rustc -Vv | grep host | sed 's/host: //')

if [ $host = 'x86_64-pc-windows-msvc' ]; then
    curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.zip -o cargo-hack.zip
    7z x cargo-hack.zip
elif [ $host = 'x86_64-apple-darwin' ] || [ $host = 'x86_64-unknown-linux-gnu' ]; then
    curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.tar.gz | tar xzf -
else
    echo "unsupported operating system"
    exit 1
fi

```

Use freely, of course.

**Comment by taiki-e** [comment]
@jhpratt Thanks, that script is really useful:)

**Comment by taiki-e** [comment]
FWIW,  if don't care about the exact name of the toolchain (usually there is no problem), using `[[ ... ]]` instead of `[]` makes it a bit simpler:

```diff
- if [ $host = 'x86_64-pc-windows-msvc' ]; then
+ if [[ $host =~ windows ]]; then
      curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.zip -o cargo-hack.zip
      7z x cargo-hack.zip
- elif [ $host = 'x86_64-apple-darwin' ] || [ $host = 'x86_64-unknown-linux-gnu' ]; then
+ elif [[ $host =~ darwin|linux ]]; then
```

**Comment by jhpratt** [comment]
That would definitely make things simpler.

I'm currently looking into how I can still add `cargo-hack` to `$PATH` for GitHub Actions. For obvious reasons I'd prefer to avoid adding the current directory to the path. I'm honestly not too familiar with what the idiomatic thing to do is if you have any suggestions?

**Comment by jhpratt** [comment]
And completely unrelated to my previous comment, it might be worth `strip`ping the binary before bundling it up. In my experience this typically reduces binary size by about two thirds.

**Comment by taiki-e** [comment]
> I'm currently looking into how I can still add `cargo-hack` to `$PATH` for GitHub Actions. For obvious reasons I'd prefer to avoid adding the current directory to the path. I'm honestly not too familiar with what the idiomatic thing to do is if you have any suggestions?

I don't know if that's the idiomatic way, but I think creating a new directory and adding that directory to `$PATH` is an easy way. Something like the following:

```sh
mkdir ci-bin
mv cargo-hack ci-bin/
echo "$(pwd)/ci-bin" >> "${GITHUB_PATH}"
```

> it might be worth `strip`ping the binary before bundling it up. In my experience this typically reduces binary size by about two thirds.

I think that's definitely a good idea, I'll try that.

**Comment by jhpratt** [comment]
I've no idea if you're familiar with the way the PATH env var works in Windows, but I certainly don't. Just reporting that doing the following [fails on CI](https://github.com/time-rs/time/runs/1371964837?check_suite_focus=true#step:7:12) (I use Linux personally, and my household doesn't have any Windows machines).

```yaml
- name: Install cargo-hack
  shell: bash
  run: |
    version=$(curl -LsSf https://api.github.com/repos/taiki-e/cargo-hack/releases/latest | jq -r '.name')
    host=$(rustc -Vv | grep host | sed 's/host: //')

    if [[ $host =~ windows ]]; then
        curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.zip -o cargo-hack.zip
        7z x cargo-hack.zip
    elif [[ $host =~ darwin|linux ]]; then
        curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.tar.gz | tar xzf -
    else
        echo "unsupported operating system"
        exit 1
    fi

    mkdir __cargo_hack_bin
    mv cargo-hack __cargo_hack_bin
    echo "$(pwd)/__cargo_hack_bin" >> $GITHUB_PATH
```

And I see that you've already implemented stripping, but given that the download is <1 second on CI in the previous link, it turns out that minor optimization will probably have an extremely small effect.

**Comment by taiki-e** [comment]
> I've no idea if you're familiar with the way the PATH env var works in Windows, but I certainly don't. Just reporting that doing the following [fails on CI](https://github.com/time-rs/time/runs/1371964837?check_suite_focus=true#step:7:12) (I use Linux personally, and my household doesn't have any Windows machines).

Hmm, it's odd that `$GITHUB_PATH` doesn't work on windows. (I thought it is the [formal way to add path](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path)...)
I think the way of moving a binary to a directory that is already in `$PATH` should probably work.
```sh
mv cargo-hack $HOME/.cargo/bin/
```

**Comment by taiki-e** [comment]
> Hmm, it's odd that `$GITHUB_PATH` doesn't work on windows. (I thought it is the [formal way to add path](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path)...)

Oh, this seems to be because the Unix style absolute path (`\c\...`) returned by `bash`'s `pwd` is not considered a valid path of Windows. So the following patches [work](https://github.com/taiki-e/test/runs/1372229357?check_suite_focus=true#step:4:49).

```diff
          7z x cargo-hack.zip
+         echo "$(pwd)/__cargo_hack_bin" | sed 's/^\///' | sed 's/\//:\\/' >> $GITHUB_PATH
      elif [[ $host =~ darwin|linux ]]; then
          curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.tar.gz | tar xzf -
+         echo "$(pwd)/__cargo_hack_bin" >> $GITHUB_PATH
      else
```
```diff
      mkdir __cargo_hack_bin
      mv cargo-hack __cargo_hack_bin
-     echo "$(pwd)/__cargo_hack_bin" >> $GITHUB_PATH
```

However, [the way mentioned in my comments above](https://github.com/taiki-e/cargo-hack/pull/89#issuecomment-723733554) is simpler.

```sh
version=$(curl -LsSf https://api.github.com/repos/taiki-e/cargo-hack/releases/latest | jq -r '.name')
host=$(rustc -Vv | grep host | sed 's/host: //')

if [[ $host =~ windows ]]; then
  curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.zip -o cargo-hack.zip
  7z x cargo-hack.zip
elif [[ $host =~ darwin|linux ]]; then
  curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.tar.gz | tar xzf -
else
  echo "unsupported operating system"
  exit 1
fi

mv cargo-hack $HOME/.cargo/bin/
```

**Comment by jhpratt** [comment]
That's some odd behavior. I pulled the `mv` behavior into the extraction, but that's just personal preference. I can confirm that this works as expected on CI.

```bash
version=$(curl -LsSf https://api.github.com/repos/taiki-e/cargo-hack/releases/latest | jq -r '.name')
host=$(rustc -Vv | grep host | sed 's/host: //')

if [[ $host =~ windows ]]; then
    curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.zip -o cargo-hack.zip
    7z x cargo-hack.zip -o ~/.cargo/bin
elif [[ $host =~ darwin|linux ]]; then
    curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-${host}.tar.gz | tar xzf - -C ~/.cargo/bin
else
    echo "unsupported operating system"
    exit 1
fi
```

**Comment by taiki-e** [comment]
Hmm, maybe it is better not to include the version number in the release binary. https://github.com/rust-embedded/cross/issues/457
That allows installing cargo-hack with one command if you know the host os.
before(current):
```sh
version=$(curl -LsSf https://api.github.com/repos/taiki-e/cargo-hack/releases/latest | jq -r '.name')
curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/v${version}/cargo-hack-v${version}-x86_64-unknown-linux-gnu.zip -o cargo-hack.zip
```
after:
```sh
curl -LsSf https://github.com/taiki-e/cargo-hack/releases/download/releases/cargo-hack-x86_64-unknown-linux-gnu.zip -o cargo-hack.zip
```
That said, this will break the CI that depends on the current URL. However, this issue can be avoided by distributing under both names until the next major version (0.5).

**Pull request merged**
