### PR TITLE
feat: Add `--rust-version` flag 

### LINKED ISSUE #196: Flag to run cargo commands with the appropriate MSRV
I'm imagining a `--rust-version` flag that would add a `+<package.rust-version>` to each underlying cargo invocation.

### PR DESCRIPTION
**Pull request by epage**
Fixes #196

### CODE REVIEW

**Comment by taiki-e** [comment]
The CI failure is due to --version-range being used to test compatibility with older versions of Cargo. It can be avoided by preventing passing --version-range when --rust-version is already passed.

https://github.com/taiki-e/cargo-hack/blob/d74e3f7980aace2c05a17e9923a8cd190c0cecce/tests/auxiliary/mod.rs#L63-L67

**Comment by epage** [comment]
Looks like its passing now

**Review by taiki-e — CHANGES_REQUESTED** [review]
LGTM

**Review by taiki-e — APPROVED** [review]
Thanks!

**Pull request merged**
